package elfinder

const (
	errMsg        = "error"
	errUnknownMsg = "errUnknown"
	errUnknownCmd = "errUnknownCmd"

	errJqui              = "errJqui"
	errNode              = "errNode"
	errURL               = "errURL"
	errAccess            = "errAccess"
	errConnect           = "errConnect"
	errAbort             = "errAbort"
	errTimeout           = "errTimeout"
	errNotFound          = "errNotFound"
	errResponse          = "errResponse"
	errConf              = "errConf"
	errJSON              = "errJSON"
	errNoVolumes         = "errNoVolumes"
	errCmdParams         = "errCmdParams"
	errDataNotJSON       = "errDataNotJSON"
	errDataEmpty         = "errDataEmpty"
	errCmdReq            = "errCmdReq"
	errOpen              = "errOpen"
	errNotFolder         = "errNotFolder"
	errNotFile           = "errNotFile"
	errRead              = "errRead"
	errWrite             = "errWrite"
	errPerm              = "errPerm"
	errLocked            = "errLocked"
	errExists            = "errExists"
	errInvName           = "errInvName"
	errFolderNotFound    = "errFolderNotFound"
	errFileNotFound      = "errFileNotFound"
	errTrgFolderNotFound = "errTrgFolderNotFound"
	errPopup             = "errPopup"
	errMkdir             = "errMkdir"
	errMkfile            = "errMkfile"
	errRename            = "errRename"
	errCopyFrom          = "errCopyFrom"
	errCopyTo            = "errCopyTo"
	errMkOutLink         = "errMkOutLink"

	errUpload          = "errUpload"
	errUploadFile      = "errUploadFile"
	errUploadNoFiles   = "errUploadNoFiles"
	errUploadTotalSize = "errUploadTotalSize"
	errUploadFileSize  = "errUploadFileSize"
	errUploadMime      = "errUploadMime"
	errUploadTransfer  = "errUploadTransfer"
	errUploadTemp      = "errUploadTemp"

	errNotReplace   = "errNotReplace"
	errReplace      = "errReplace"
	errSave         = "errSave"
	errCopy         = "errCopy"
	errMove         = "errMove"
	errCopyInItself = "errCopyInItself"
	errRm           = "errRm"
	errRmSrc        = "errRmSrc"
	errExtract      = "errExtract"
	errArchive      = "errArchive"
	errArcType      = "errArcType"
	errNoArchive    = "errNoArchive"
	errCmdNoSupport = "errCmdNoSupport"
	errReplByChild  = "errReplByChild"
	errArcSymlinks  = "errArcSymlinks"
	errArcMaxSize   = "errArcMaxSize"

	errResize         = "errResize"
	errResizeDegree   = "errResizeDegree"
	errResizeRotate   = "errResizeRotate"
	errResizeSize     = "errResizeSize"
	errResizeNoChange = "errResizeNoChange"

	errUsupportType   = "errUsupportType"
	errNotUTF8Content = "errNotUTF8Content"

	errNetMount         = "errNetMount"
	errNetMountNoDriver = "errNetMountNoDriver"
	errNetMountFailed   = "errNetMountFailed"
	errNetMountHostReq  = "errNetMountHostReq"

	errSessionExpires  = "errSessionExpires"
	errCreatingTempDir = "errCreatingTempDir"

	errFtpDownloadFile = "errFtpDownloadFile"
	errFtpUploadFile   = "errFtpUploadFile"
	errFtpMkdir        = "errFtpMkdir"

	errArchiveExec   = "errArchiveExec"
	errExtractExec   = "errExtractExec"
	errNetUnMount    = "errNetUnMount"
	errConvUTF8      = "errConvUTF8"
	errFolderUpload  = "errFolderUpload"
	errSearchTimeout = "errSearchTimeout"
	errReauthRequire = "errReauthRequire"
	errMaxTargets    = "errMaxTargets"
)
