package elfinder

type ErrType string

const (
	ERRMsg        ErrType = "error"
	ERRUnknownMsg ErrType = "errUnknown"
	ERRUnknownCmd ErrType = "errUnknownCmd"

	ERRJqui              ErrType = "errJqui"
	ERRNode              ErrType = "errNode"
	ERRURL               ErrType = "errURL"
	ERRAccess            ErrType = "errAccess"
	ERRConnect           ErrType = "errConnect"
	ERRAbort             ErrType = "errAbort"
	ERRTimeout           ErrType = "errTimeout"
	ERRNotFound          ErrType = "errNotFound"
	ERRResponse          ErrType = "errResponse"
	ERRConf              ErrType = "errConf"
	ERRJSON              ErrType = "errJSON"
	ERRNoVolumes         ErrType = "errNoVolumes"
	ERRCmdParams         ErrType = "errCmdParams"
	ERRDataNotJSON       ErrType = "errDataNotJSON"
	ERRDataEmpty         ErrType = "errDataEmpty"
	ERRCmdReq            ErrType = "errCmdReq"
	ERROpen              ErrType = "errOpen"
	ERRNotFolder         ErrType = "errNotFolder"
	ERRNotFile           ErrType = "errNotFile"
	ERRRead              ErrType = "errRead"
	ERRWrite             ErrType = "errWrite"
	ERRPerm              ErrType = "errPerm"
	ERRLocked            ErrType = "errLocked"
	ERRExists            ErrType = "errExists"
	ERRInvName           ErrType = "errInvName"
	ERRFolderNotFound    ErrType = "errFolderNotFound"
	ERRFileNotFound      ErrType = "errFileNotFound"
	ERRTrgFolderNotFound ErrType = "errTrgFolderNotFound"
	ERRPopup             ErrType = "errPopup"
	ERRMkdir             ErrType = "errMkdir"
	ERRMkfile            ErrType = "errMkfile"
	ERRRename            ErrType = "errRename"
	ERRCopyFrom          ErrType = "errCopyFrom"
	ERRCopyTo            ErrType = "errCopyTo"
	ERRMkOutLink         ErrType = "errMkOutLink"

	ERRUpload          ErrType = "errUpload"
	ERRUploadFile      ErrType = "errUploadFile"
	ERRUploadNoFiles   ErrType = "errUploadNoFiles"
	ERRUploadTotalSize ErrType = "errUploadTotalSize"
	ERRUploadFileSize  ErrType = "errUploadFileSize"
	ERRUploadMime      ErrType = "errUploadMime"
	ERRUploadTransfer  ErrType = "errUploadTransfer"
	ERRUploadTemp      ErrType = "errUploadTemp"
	ERR
	ERRNotReplace   ErrType = "errNotReplace"
	ERRReplace      ErrType = "errReplace"
	ERRSave         ErrType = "errSave"
	ERRCopy         ErrType = "errCopy"
	ERRMove         ErrType = "errMove"
	ERRCopyInItself ErrType = "errCopyInItself"
	ERRRm           ErrType = "errRm"
	ERRRmSrc        ErrType = "errRmSrc"
	ERRExtract      ErrType = "errExtract"
	ERRArchive      ErrType = "errArchive"
	ERRArcType      ErrType = "errArcType"
	ERRNoArchive    ErrType = "errNoArchive"
	ERRCmdNoSupport ErrType = "errCmdNoSupport"
	ERRReplByChild  ErrType = "errReplByChild"
	ERRArcSymlinks  ErrType = "errArcSymlinks"
	ERRArcMaxSize   ErrType = "errArcMaxSize"

	ERRResize         ErrType = "errResize"
	ERRResizeDegree   ErrType = "errResizeDegree"
	ERRResizeRotate   ErrType = "errResizeRotate"
	ERRResizeSize     ErrType = "errResizeSize"
	ERRResizeNoChange ErrType = "errResizeNoChange"

	ERRUsupportType   ErrType = "errUsupportType"
	ERRNotUTF8Content ErrType = "errNotUTF8Content"

	ERRNetMount         ErrType = "errNetMount"
	ERRNetMountNoDriver ErrType = "errNetMountNoDriver"
	ERRNetMountFailed   ErrType = "errNetMountFailed"
	ERRNetMountHostReq  ErrType = "errNetMountHostReq"

	ERRSessionExpires  ErrType = "errSessionExpires"
	ERRCreatingTempDir ErrType = "errCreatingTempDir"

	ERRFtpDownloadFile ErrType = "errFtpDownloadFile"
	ERRFtpUploadFile   ErrType = "errFtpUploadFile"
	ERRFtpMkdir        ErrType = "errFtpMkdir"
	ERRArchiveExec     ErrType = "errArchiveExec"

	ERRExtractExec   ErrType = "errExtractExec"
	ERRNetUnMount    ErrType = "errNetUnMount"
	ERRConvUTF8      ErrType = "errConvUTF8"
	ERRFolderUpload  ErrType = "errFolderUpload"
	ERRSearchTimeout ErrType = "errSearchTimeout"
	ERRReauthRequire ErrType = "errReauthRequire"
	ERRMaxTargets    ErrType = "errMaxTargets"
)
